/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ims.gui;

import Uilt.CheckDataEntity;
import javax.swing.ImageIcon;
import Uilt.Alert;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import BLL.LoadDataCbxBLL;
import BLL.NVBLL;
import MODEL.BacLuongReponseModel;
import MODEL.ChucVuReponseModel;
import MODEL.ChuyenMonReponseModel;
import MODEL.DanTocReponseModel;
import MODEL.GiaDinhReponseModel;
import MODEL.GioiTinhReponseModel;

import MODEL.MaHopDongReponseModel;
import MODEL.PhongBanReponseModel;
import MODEL.TonGiaoReponseModel;
import MODEL.TrinhDoReponseModel;
import MODEL.NVModel;
import com.sun.xml.internal.ws.message.ByteArrayAttachment;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author NAT
 */
public class NhanVienThem extends javax.swing.JFrame {

    ResultSet result;
    LoadDataCbxBLL dataCbxBLL = new LoadDataCbxBLL();
    NVBLL nvBLL = new NVBLL();
    NVModel nVModel;
    String filename = null;
    byte[] person_image = null;
    GioiTinhReponseModel gt = new GioiTinhReponseModel();
    GiaDinhReponseModel gd = new GiaDinhReponseModel();
    DanTocReponseModel dt = new DanTocReponseModel();
    TonGiaoReponseModel tg = new TonGiaoReponseModel();
    BacLuongReponseModel bl = new BacLuongReponseModel();
    MaHopDongReponseModel hd = new MaHopDongReponseModel();

    public NhanVienThem() {
        initComponents();
        stateButton(true);
        setInfoDialog();
        initCombobox();
    }

    public void setInfoDialog() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
        setResizable(false);
    }

    public void stateButton(boolean value) {

//        btNew.setVisible(value);
//        btEdit.setVisible(value);
//        btDelete.setVisible(value);
//        btPrint.setVisible(value);
//        btClose.setVisible(value);
        jButtonHuy.setVisible(value);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonHuy = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMaNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldHoten = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMaphong = new javax.swing.JTextField();
        jComboBoxMaphong = new javax.swing.JComboBox();
        jComboBoxChucvu = new javax.swing.JComboBox();
        jTextFieldChucvu = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxMatrinhdo = new javax.swing.JComboBox();
        jComboBoxChuyenmon = new javax.swing.JComboBox();
        jTextFieldMatrinhdo = new javax.swing.JTextField();
        jTextFieldChuyenmon = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxGioitinh = new javax.swing.JComboBox();
        jTextFieldNoisinh = new javax.swing.JTextField();
        jTextFieldSoCMND = new javax.swing.JTextField();
        jComboBoxDantoc = new javax.swing.JComboBox();
        jTextFieldQuequan = new javax.swing.JTextField();
        jTextFieldChohientai = new javax.swing.JTextField();
        jTextFieldSDT = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldNgaysinh = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jComboBoxGiaDinh = new javax.swing.JComboBox();
        jComboBoxTonGiao = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldSoHDLD = new javax.swing.JTextField();
        jComboBoxMaHD = new javax.swing.JComboBox();
        jTextFieldLoaiHD = new javax.swing.JTextField();
        jTextFieldNgayHD = new javax.swing.JTextField();
        jTextFieldNgayBD = new javax.swing.JTextField();
        jTextFieldNgayKT = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabelHinhanh = new javax.swing.JLabel();
        jButtonTim = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldPhucapCV = new javax.swing.JTextField();
        jComboBoxBacluong = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jButtonLuu = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonHuy.setText("Hủy");
        jButtonHuy.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã NV:");

        jLabel2.setText("Họ và tên:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Đơn vị");

        jLabel4.setText("Mã Phòng:");

        jLabel5.setText("Chức vụ:");

        jComboBoxMaphong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMaphongItemStateChanged(evt);
            }
        });
        jComboBoxMaphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMaphongActionPerformed(evt);
            }
        });

        jComboBoxChucvu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxChucvuItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxChucvu, 0, 116, Short.MAX_VALUE)
                            .addComponent(jComboBoxMaphong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMaphong)
                            .addComponent(jTextFieldChucvu, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxMaphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMaphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jLabel6.setText("Trình độ");

        jLabel7.setText("Mã trình độ:");

        jLabel8.setText("Chuyên môn:");

        jComboBoxMatrinhdo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMatrinhdoItemStateChanged(evt);
            }
        });

        jComboBoxChuyenmon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxChuyenmonItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxMatrinhdo, 0, 109, Short.MAX_VALUE)
                            .addComponent(jComboBoxChuyenmon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMatrinhdo, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jTextFieldChuyenmon))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxMatrinhdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMatrinhdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxChuyenmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldChuyenmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel9.setText("Thông tin");

        jLabel10.setText("Giới tính:");

        jLabel11.setText("Nơi sinh:");

        jLabel12.setText("Số CMND:");

        jLabel13.setText("Dân tộc:");

        jLabel14.setText("Quê quán:");

        jLabel15.setText("Chỗ ở hiện tại:");

        jLabel16.setText("SĐT:");

        jComboBoxGioitinh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxGioitinhItemStateChanged(evt);
            }
        });
        jComboBoxGioitinh.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jComboBoxGioitinhInputMethodTextChanged(evt);
            }
        });

        jComboBoxDantoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDantocItemStateChanged(evt);
            }
        });

        jLabel17.setText("Ngày sinh:");

        jLabel19.setText("Gia đình");

        jLabel31.setText("Tôn giáo");

        jComboBoxGiaDinh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxGiaDinhItemStateChanged(evt);
            }
        });

        jComboBoxTonGiao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTonGiaoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldQuequan, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                            .addComponent(jTextFieldChohientai)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jComboBoxGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNgaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                                .addComponent(jTextFieldNoisinh, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldSoCMND, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jComboBoxDantoc, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel31)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBoxTonGiao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBoxGiaDinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addComponent(jTextFieldSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldNoisinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jComboBoxDantoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jComboBoxGiaDinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jComboBoxTonGiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldQuequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldChohientai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(0, 50, Short.MAX_VALUE))
        );

        jLabel24.setText("Hợp đồng lao động");

        jLabel25.setText("HĐLĐ số:");

        jLabel26.setText("Mã HĐ:");

        jLabel27.setText("Loại HĐ:");

        jLabel28.setText("Ngày HĐ:");

        jLabel29.setText("Ngày BĐ:");

        jLabel30.setText("Ngày KT:");

        jComboBoxMaHD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMaHDItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSoHDLD, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldLoaiHD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNgayHD, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 263, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldSoHDLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jComboBoxMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextFieldLoaiHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jTextFieldNgayHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextFieldNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextFieldNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jLabel18.setText("Hình ảnh");

        jButtonTim.setText("Tìm");
        jButtonTim.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimActionPerformed(evt);
            }
        });

        jButtonXoa.setText("Xóa");
        jButtonXoa.setPreferredSize(new java.awt.Dimension(75, 23));

        jLabel20.setText("Lương");

        jLabel21.setText("Bậc lương:");

        jLabel22.setText("Phụ cấp CV:");

        jComboBoxBacluong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxBacluongItemStateChanged(evt);
            }
        });

        jLabel23.setText("VNĐ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxBacluong, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPhucapCV, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(0, 35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jComboBoxBacluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldPhucapCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel18))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonLuu.setText("Lưu");
        jButtonLuu.setFocusable(false);
        jButtonLuu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLuu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuuActionPerformed(evt);
            }
        });

        jLabel32.setText("jLabel32");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel32))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jButtonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(jButtonLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(151, 151, 151)))
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLuu))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
         if(JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát không?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==0) {
            System.exit(0); 
        } 
    }//GEN-LAST:event_jButtonHuyActionPerformed

    private void jComboBoxMaphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMaphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMaphongActionPerformed

    private void jButtonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuuActionPerformed
        // TODO add your handling code here:
        
//        int maNV = Integer.parseInt(jTextFieldMaNV.getText());
//        String hoTen = jTextFieldHoten.getText();
//        String maPhong = jTextFieldMaphong.getText();
//        String chucVu = jTextFieldChucvu.getText();
//        String maTrinhDo = jTextFieldMatrinhdo.getText();
//        String chuyenMon = jTextFieldChuyenmon.getText();
//        String gioiTinh = jComboBoxGioitinh.getSelectedItem().toString();
//        String ngaySinh = jTextFieldNgaysinh.getText();
//       
//      
//        String noiSinh = jTextFieldNoisinh.getText();
//        int soCMND = Integer.parseInt(jTextFieldSoCMND.getText());
//        String giaDinh = jComboBoxGiaDinh.getSelectedItem().toString();
//        String danToc = jComboBoxDantoc.getSelectedItem().toString();
//        String tonGiao = jComboBoxTonGiao.getSelectedItem().toString();
//        String queQuan = jTextFieldQuequan.getText();
//        String choOHienTai = jTextFieldChohientai.getText();
//        int dienThoaiDD = Integer.parseInt(jTextFieldSDT.getText());
//        String bacLuong = jComboBoxBacluong.getSelectedItem().toString();
//        String phuCapCV = jTextFieldPhucapCV.getText();
//        String hdldSo = jTextFieldSoHDLD.getText();
//        String maHD = jComboBoxMaHD.getSelectedItem().toString();
//        String loaiHD = jTextFieldLoaiHD.getText();
////        int ngayHD = Integer.parseInt(txtNgayHD.getText());
////        int ngayBD = Integer.parseInt(txtNgayBD.getText());
////        int ngayKT = Integer.parseInt(txtNgayKT.getText());
//        nVModel.setMaNV(maNV);
//        nVModel.setHoTenNV(hoTen);
//        nVModel.setKHPhongBan(maPhong);
//        nVModel.setKHChucVu(chucVu);
//        nVModel.setKHTrinhDo(maTrinhDo);
//        nVModel.setKHChuyenMon(chuyenMon);
//        nVModel.setGioiTinh(gioiTinh);
//        
//        nVModel.setNoiSinh(noiSinh);
//        nVModel.setSoCMND(soCMND);
//        nVModel.setGiaDinh(giaDinh);
//        nVModel.setTenDanToc(danToc);
//        nVModel.setTenTonGiao(tonGiao);
//        nVModel.setQueQuan(queQuan);
//        nVModel.setChoHienTai(choOHienTai);
//        nVModel.setSDT(dienThoaiDD);
//        nVModel.setGiaBacLuong(bacLuong);
//        nVModel.setPhuCapCV(phuCapCV);
//        nVModel.setHDLDSo(hdldSo);
//        nVModel.setTenHopDong(maHD);
//        nVModel.setLoaiHD(loaiHD);
//        
//        nVModel.setGioiTinh(gt.getGioiTinh());
//        nVModel.setMaGiaDinh(gd.getGiaDinh());
//        nVModel.setMaDanToc(dt.getTenDanToc());
//        nVModel.setMaTonGiao(tg.getMaTonGiao());
//        nVModel.setMaBacLuong(bl.getMaBacLuong());
//        addnewNV.addNewNhanVienBLL(nhanVien);
//        
//                                        
    }//GEN-LAST:event_jButtonLuuActionPerformed

    private void jComboBoxDantocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDantocItemStateChanged
        // TODO add your handling code here:

        DanTocReponseModel itemDanToc = (DanTocReponseModel) jComboBoxDantoc.getSelectedItem();
        int idDanToc = itemDanToc.getIDDanToc();
//         String iTenDanToc = itemDanToc.getTenDanToc(); 
//         System.out.println("ID" + idDanToc + "\nTenDanToc" + iTenDanToc);
//        jTextFieldQuequan.setText(iTenDanToc);

    }//GEN-LAST:event_jComboBoxDantocItemStateChanged

    private void jComboBoxMaHDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMaHDItemStateChanged
        // TODO add your handling code here:
        MaHopDongReponseModel itemMHD = (MaHopDongReponseModel) jComboBoxMaHD.getSelectedItem();
        int idMaHD = itemMHD.getIDHopDong();
        String iTenHD = itemMHD.getTenHopDong();
        jTextFieldLoaiHD.setText(iTenHD);
    }//GEN-LAST:event_jComboBoxMaHDItemStateChanged

    private void jComboBoxMaphongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMaphongItemStateChanged
        // TODO add your handling code here:
        PhongBanReponseModel itemPhongBan = (PhongBanReponseModel) jComboBoxMaphong.getSelectedItem();
        String idMaPB = itemPhongBan.getKHPhongBan();
        String iTenPB = itemPhongBan.getTenPhongBan();
        jTextFieldMaphong.setText(iTenPB);
    }//GEN-LAST:event_jComboBoxMaphongItemStateChanged

    private void jComboBoxChucvuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxChucvuItemStateChanged
        // TODO add your handling code here:
        ChucVuReponseModel itemChucVu = (ChucVuReponseModel) jComboBoxChucvu.getSelectedItem();
        String idMaCV = itemChucVu.getKHChucVu();
        String iTenCV = itemChucVu.getTenChucVu();
        jTextFieldChucvu.setText(iTenCV);
    }//GEN-LAST:event_jComboBoxChucvuItemStateChanged

    private void jComboBoxMatrinhdoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMatrinhdoItemStateChanged
        // TODO add your handling code here:
        TrinhDoReponseModel itemTrinhDo = (TrinhDoReponseModel) jComboBoxMatrinhdo.getSelectedItem();
        String idMaTD = itemTrinhDo.getKHTrinhDo();
        String iTenTD = itemTrinhDo.getTenTrinhDo();
        jTextFieldMatrinhdo.setText(iTenTD);
    }//GEN-LAST:event_jComboBoxMatrinhdoItemStateChanged

    private void jComboBoxChuyenmonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxChuyenmonItemStateChanged
        // TODO add your handling code here:
        ChuyenMonReponseModel itemChuyenMon = (ChuyenMonReponseModel) jComboBoxChuyenmon.getSelectedItem();
        String idMaCM = itemChuyenMon.getKHChuyenMon();
        String iTenCM = itemChuyenMon.getTenChuyenMon();
        jTextFieldChuyenmon.setText(iTenCM);
    }//GEN-LAST:event_jComboBoxChuyenmonItemStateChanged

    private void jButtonTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(jLabelHinhanh.getWidth(), jLabelHinhanh.getHeight(), Image.SCALE_SMOOTH));
        jLabelHinhanh.setIcon(imageIcon);
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }
            person_image = bos.toByteArray();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NhanVienThem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NhanVienThem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonTimActionPerformed

    private void jComboBoxGioitinhInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxGioitinhInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGioitinhInputMethodTextChanged

    private void jComboBoxGioitinhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxGioitinhItemStateChanged
        GioiTinhReponseModel itemGioiTinh = (GioiTinhReponseModel) jComboBoxGioitinh.getSelectedItem();
        String TenGioiTinh = itemGioiTinh.getGioiTinh();

    }//GEN-LAST:event_jComboBoxGioitinhItemStateChanged

    private void jComboBoxTonGiaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTonGiaoItemStateChanged
        // TODO add your handling code here:
        TonGiaoReponseModel itemTonGiao = (TonGiaoReponseModel) jComboBoxTonGiao.getSelectedItem();
        int idTonGiao = itemTonGiao.getIDTonGiao();
    }//GEN-LAST:event_jComboBoxTonGiaoItemStateChanged

    private void jComboBoxBacluongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxBacluongItemStateChanged
        // TODO add your handling code here:
        BacLuongReponseModel itemBacLuong = (BacLuongReponseModel) jComboBoxBacluong.getSelectedItem();
        int idBacLuong = itemBacLuong.getIDBacLuong();
    }//GEN-LAST:event_jComboBoxBacluongItemStateChanged

    private void jComboBoxGiaDinhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxGiaDinhItemStateChanged
        // TODO add your handling code here:
        GiaDinhReponseModel itemGiaDinh = (GiaDinhReponseModel) jComboBoxGiaDinh.getSelectedItem();
        String TenGiaDinh = itemGiaDinh.getGiaDinh();
    }//GEN-LAST:event_jComboBoxGiaDinhItemStateChanged

    private void initCombobox() {
        jComboBoxDantoc();
        jComboBoxTonGiao();
        jComboBoxBacLuong();
        jComboBoxMaHopDong();
        jComboBoxChuyenMon();
        jComboBoxTrinhDo();
        jComboBoxPhongBan();
        jComboBoxChucVu();
        jComboBoxGiaDinh();
        jComboBoxGioiTinh();
    }

    private void jComboBoxDantoc() {
        result = dataCbxBLL.layDanTocBLL();

        try {
            while (result.next()) {
                int id = Integer.parseInt(result.getString(1));
                String name = result.getString(2);
                jComboBoxDantoc.addItem(new DanTocReponseModel(id, name));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienThem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     private void jComboBoxGiaDinh() {
        result = dataCbxBLL.layGiaDinhBLL();

        try {
            while (result.next()) {
                int id = Integer.parseInt(result.getString(1));
                String name = result.getString(2);
                jComboBoxGiaDinh.addItem(new GiaDinhReponseModel(id, name));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienThem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
  private void jComboBoxGioiTinh() {
        result = dataCbxBLL.layGioiTinhBLL();

        try {
            while (result.next()) {
                int id = Integer.parseInt(result.getString(1));
                String name = result.getString(2);
                jComboBoxGioitinh.addItem(new GioiTinhReponseModel(id, name));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienThem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jComboBoxTonGiao() {
        result = dataCbxBLL.layTonGiaoBLL();
        try {
            while (result.next()) {
                int id = Integer.parseInt(result.getString(1));
                String name = result.getString(2);
                jComboBoxTonGiao.addItem(new TonGiaoReponseModel(id, name));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienThem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void jComboBoxBacLuong() {
        result = dataCbxBLL.layBacLuongBLL();
        try {
            while (result.next()) {
                int id = Integer.parseInt(result.getString(1));
                String name = result.getString(2);
                jComboBoxBacluong.addItem(new BacLuongReponseModel(id, name));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienThem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void jComboBoxMaHopDong() {
        result = dataCbxBLL.layMaHopDongBLL();
        try {
            while (result.next()) {
                int id = Integer.parseInt(result.getString(1));
                String name = result.getString(2);
                jComboBoxMaHD.addItem(new MaHopDongReponseModel(id, name));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienThem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void jComboBoxChuyenMon() {
        result = dataCbxBLL.layChuyenMonBLL();
        try {
            while (result.next()) {
                String id = result.getString(1);
                String name = result.getString(2);
                jComboBoxChuyenmon.addItem(new ChuyenMonReponseModel(id, name));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienThem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void jComboBoxTrinhDo() {
        result = dataCbxBLL.layTrinhDoBLL();
        try {
            while (result.next()) {
                String id = result.getString(1);
                String name = result.getString(2);
                jComboBoxMatrinhdo.addItem(new TrinhDoReponseModel(id, name));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienThem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void jComboBoxChucVu() {
        result = dataCbxBLL.layChucVuBLL();
        try {
            while (result.next()) {
                String id = result.getString(1);
                String name = result.getString(2);
                jComboBoxChucvu.addItem(new ChucVuReponseModel(id, name));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienThem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void jComboBoxPhongBan() {
        result = dataCbxBLL.layPhongBanBLL();
        try {
            while (result.next()) {
                String id = result.getString(1);
                String name = result.getString(2);
                jComboBoxMaphong.addItem(new PhongBanReponseModel(id, name));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhanVienThem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienThem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JButton jButtonTim;
    private javax.swing.JButton jButtonXoa;
    public javax.swing.JComboBox jComboBoxBacluong;
    public javax.swing.JComboBox jComboBoxChucvu;
    public javax.swing.JComboBox jComboBoxChuyenmon;
    public javax.swing.JComboBox jComboBoxDantoc;
    public javax.swing.JComboBox jComboBoxGiaDinh;
    public javax.swing.JComboBox jComboBoxGioitinh;
    public javax.swing.JComboBox jComboBoxMaHD;
    public javax.swing.JComboBox jComboBoxMaphong;
    public javax.swing.JComboBox jComboBoxMatrinhdo;
    public javax.swing.JComboBox jComboBoxTonGiao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelHinhanh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JTextField jTextFieldChohientai;
    public javax.swing.JTextField jTextFieldChucvu;
    public javax.swing.JTextField jTextFieldChuyenmon;
    public javax.swing.JTextField jTextFieldHoten;
    public javax.swing.JTextField jTextFieldLoaiHD;
    public javax.swing.JTextField jTextFieldMaNV;
    public javax.swing.JTextField jTextFieldMaphong;
    public javax.swing.JTextField jTextFieldMatrinhdo;
    public javax.swing.JTextField jTextFieldNgayBD;
    public javax.swing.JTextField jTextFieldNgayHD;
    public javax.swing.JTextField jTextFieldNgayKT;
    public javax.swing.JTextField jTextFieldNgaysinh;
    public javax.swing.JTextField jTextFieldNoisinh;
    public javax.swing.JTextField jTextFieldPhucapCV;
    public javax.swing.JTextField jTextFieldQuequan;
    public javax.swing.JTextField jTextFieldSDT;
    public javax.swing.JTextField jTextFieldSoCMND;
    public javax.swing.JTextField jTextFieldSoHDLD;
    // End of variables declaration//GEN-END:variables

}
